---
platform: linux
image: docker:///boshcpi/cpi-certification

inputs:
  - name: pipelines
  - name: environment

outputs:
  - name: bats-config

run:
  path: pipelines/vsphere/tasks/prepare-bats.sh

params:
  STEMCELL_NAME:          ""
  BAT_VCAP_PASSWORD:      ""
  BOSH_DIRECTOR_USER:     ""
  BOSH_DIRECTOR_PASSWORD: ""
