---
groups:
  - name: certify-aws
    jobs:
      - bats-centos
      - bats-ubuntu
      - end2end-us
      - certify-centos
      - certify-ubuntu
      - prepare-infrastructure
      - teardown-infrastructure

shared:
  - &prepare-director
    task: prepare-director
    file: pipelines/aws/tasks/prepare-director.yml
    config:
      params:
          BOSH_RELEASE_URI:       file://bosh-release/release.tgz
          CPI_RELEASE_URI:        file://cpi-release/release.tgz
          STEMCELL_URI:           file://stemcell/stemcell.tgz
          BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
          BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}
          AWS_ACCESS_KEY:         {{AWS_ACCESS_KEY}}
          AWS_SECRET_KEY:         {{AWS_SECRET_KEY}}
          AWS_REGION_NAME:        {{AWS_REGION_NAME}}
          PUBLIC_KEY_NAME:        {{PUBLIC_KEY_NAME}}
          PRIVATE_KEY_DATA:       {{PRIVATE_KEY_DATA}}
          AWS_STACK_NAME:         ""
          AWS_STACK_PREFIX:       ""

  - &deploy-director
    task: deploy-director
    file: pipelines/shared/tasks/deploy-director.yml
    config:
      params:
        BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
        BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}

  - &prepare-manual-bats
    task: prepare-manual-bats
    file: pipelines/aws/tasks/prepare-manual-bats.yml
    config:
      params:
        AWS_ACCESS_KEY:         {{AWS_ACCESS_KEY}}
        AWS_SECRET_KEY:         {{AWS_SECRET_KEY}}
        AWS_REGION_NAME:        {{AWS_REGION_NAME}}
        AWS_STACK_NAME:         {{AWS_BATS_STACK_NAME}}
        BAT_VCAP_PASSWORD:      {{BAT_VCAP_PASSWORD}}
        PUBLIC_KEY_NAME:        {{PUBLIC_KEY_NAME}}
        BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
        BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}
        STEMCELL_NAME:          ""
        AWS_STACK_PREFIX:       ""

  - &run-bats
    task: run-bats
    file: pipelines/shared/tasks/run-bats.yml

  - &run-e2e
    task: run-e2e
    file: pipelines/aws/tasks/run-e2e.yml
    params:
      AWS_ACCESS_KEY:         {{AWS_ACCESS_KEY}}
      AWS_SECRET_KEY:         {{AWS_SECRET_KEY}}
      AWS_REGION_NAME:        {{AWS_REGION_NAME}}
      BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
      BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}
      AWS_STACK_NAME:         {{AWS_E2E_STACK_NAME}}
      AWS_STACK_PREFIX:       ""
      STEMCELL_NAME:          ""

  - &teardown
    task: teardown
    file: pipelines/shared/tasks/teardown.yml
    config:
      params:
        BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
        BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}
        DEPLOYMENT_NAME:        certification

jobs:
  - name: end2end-us
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: stemcell,        trigger: true, resource: ubuntu-stemcell}
        - {get: centos-stemcell, trigger: false} # pass-thru to certification jobs
        - {get: pipelines,       trigger: false}
        - {get: bosh-init,       trigger: false}

      - <<: *prepare-director
        config:
          params:
            AWS_STACK_NAME:   {{AWS_E2E_STACK_NAME}}
            AWS_STACK_PREFIX: Ubuntu
            USE_IAM:          true

      - do:
          - <<: *deploy-director

          - <<: *run-e2e
            params:
              STEMCELL_NAME:    *ubuntu-stemcell
              AWS_STACK_PREFIX: Ubuntu

        ensure:
          <<: *teardown
          config:
            params:
              DEPLOYMENT_NAME: e2e-test

  - name: bats-centos
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true}
        - {get: cpi-release,  trigger: true}
        - {get: stemcell,     trigger: true, resource: centos-stemcell}
        - {get: pipelines,    trigger: false}
        - {get: bosh-init,    trigger: false}
        - {get: bats,         trigger: false}

      - <<: *prepare-director
        config:
          params:
            AWS_STACK_NAME:   {{AWS_BATS_STACK_NAME}}
            AWS_STACK_PREFIX: Centos

      - do:
          - <<: *deploy-director

          - <<: *prepare-manual-bats
            config:
              params:
                STEMCELL_NAME:    *centos-stemcell
                AWS_STACK_PREFIX: Centos

          - <<: *run-bats

        ensure:
          <<: *teardown

  - name: bats-ubuntu
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true}
        - {get: cpi-release,  trigger: true}
        - {get: stemcell,     trigger: true, resource: ubuntu-stemcell}
        - {get: pipelines,    trigger: false}
        - {get: bosh-init,    trigger: false}
        - {get: bats,         trigger: false}

      - <<: *prepare-director
        config:
          params:
            AWS_STACK_NAME:   {{AWS_BATS_STACK_NAME}}
            AWS_STACK_PREFIX: Ubuntu

      - do:
          - <<: *deploy-director

          - <<: *prepare-manual-bats
            config:
              params:
                STEMCELL_NAME:    *ubuntu-stemcell
                AWS_STACK_PREFIX: Ubuntu

          - <<: *run-bats
        ensure:
          <<: *teardown

  - name: certify-centos
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-centos, end2end-us]}
        - {get: cpi-release,  trigger: true, passed: [bats-centos, end2end-us]}
        - {get: stemcell,     trigger: true, passed: [bats-centos, end2end-us], resource: centos-stemcell}
        - {get: pipelines,    trigger: false}

      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        config:
          params:
            CPI_RELEASE_NAME: bosh-aws-cpi
            STEMCELL_NAME:    *centos-stemcell

      - {put: receipt, params: {file: certification/*-receipt.json}}

  - name: certify-ubuntu
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-ubuntu, end2end-us]}
        - {get: cpi-release,  trigger: true, passed: [bats-ubuntu, end2end-us]}
        - {get: stemcell,     trigger: true, passed: [bats-ubuntu, end2end-us], resource: ubuntu-stemcell}
        - {get: pipelines,    trigger: false}

      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        config:
          params:
            CPI_RELEASE_NAME: bosh-aws-cpi
            STEMCELL_NAME:    *ubuntu-stemcell

      - {put: receipt, params: {file: certification/*-receipt.json}}

  - name: prepare-infrastructure
    plan:
      - {get: pipelines, trigger: false}
      - aggregate:
        - task: prepare-bats-infrastructure
          file: pipelines/aws/tasks/prepare-infrastructure.yml
          config:
            params:
              AWS_STACK_TEMPLATE: bats-promotion
              AWS_STACK_NAME:     {{AWS_BATS_STACK_NAME}}
              AWS_ACCESS_KEY:     {{AWS_ACCESS_KEY}}
              AWS_SECRET_KEY:     {{AWS_SECRET_KEY}}
              AWS_REGION_NAME:    {{AWS_REGION_NAME}}
        - task: prepare-e2e-infrastructure
          file: pipelines/aws/tasks/prepare-infrastructure.yml
          config:
            params:
              AWS_STACK_TEMPLATE: end2end
              AWS_STACK_NAME:     {{AWS_E2E_STACK_NAME}}
              AWS_ACCESS_KEY:     {{AWS_ACCESS_KEY}}
              AWS_SECRET_KEY:     {{AWS_SECRET_KEY}}
              AWS_REGION_NAME:    {{AWS_REGION_NAME}}

  - name: teardown-infrastructure
    plan:
      - {get: pipelines, trigger: false}
      - aggregate:
        - task: teardown-bats-infrastructure
          file: pipelines/aws/tasks/teardown-infrastructure.yml
          config:
            params:
              AWS_ACCESS_KEY:  {{AWS_ACCESS_KEY}}
              AWS_SECRET_KEY:  {{AWS_SECRET_KEY}}
              AWS_REGION_NAME: {{AWS_REGION_NAME}}
              AWS_STACK_NAME:  {{AWS_BATS_STACK_NAME}}
        - task: teardown-e2e-infrastructure
          file: pipelines/aws/tasks/teardown-infrastructure.yml
          config:
            params:
              AWS_ACCESS_KEY:  {{AWS_ACCESS_KEY}}
              AWS_SECRET_KEY:  {{AWS_SECRET_KEY}}
              AWS_REGION_NAME: {{AWS_REGION_NAME}}
              AWS_STACK_NAME:  {{AWS_E2E_STACK_NAME}}

resources:
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master

  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-aws-cpi-release

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: centos-stemcell
    type: bosh-io-stemcell
    source:
      name: &centos-stemcell bosh-aws-xen-hvm-centos-7-go_agent

  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: &ubuntu-stemcell bosh-aws-xen-hvm-ubuntu-trusty-go_agent

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: bosh-init-artifacts
      region_name: us-east-1

  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-receipt\.json
      region_name: us-east-1
