---
groups:
  - name: certify-aws
    jobs:
      - bats-centos
      - bats-ubuntu
      - test-upgrade
      - certify-centos
      - certify-ubuntu

shared:
  - &prepare-director
    task: prepare-director
    file: pipelines/aws/tasks/prepare-director.yml
    config:
      params:

  - &deploy-director
    task: deploy-director
    file: pipelines/shared/tasks/deploy-director.yml
    config:
      params:
        BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
        BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}

  - &run-bats
    task: run-bats
    file: pipelines/shared/tasks/run-bats.yml
    config:
      params:
        BAT_STEMCELL_NAME: ""
        BAT_VCAP_PASSWORD: {{BAT_VCAP_PASSWORD}}

  - &teardown
    task: teardown
    file: pipelines/shared/tasks/teardown.yml
    config:
      params:
        BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
        BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}
        DEPLOYMENT_NAME:        certification

jobs:
  - name: bats-centos
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true}
        - {get: cpi-release,  trigger: true}
        - {get: stemcell,     trigger: true, resource: centos-stemcell}
        - {get: pipelines,    trigger: false}
        - {get: bosh-init,    trigger: false}
        - {get: bats,         trigger: false}

      - {put: environment, params: {acquire: true}}

      - <<: *prepare-director

      - <<: *deploy-director

      - <<: *run-bats
        config:
          params:
            BAT_STEMCELL_NAME: bosh-aws-xen-centos-7-go_agent

      - <<: *teardown

      - {put: environment, params: {release: environment}}

  - name: bats-ubuntu
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true}
        - {get: cpi-release,  trigger: true}
        - {get: stemcell,     trigger: true, resource: ubuntu-stemcell}
        - {get: pipelines,    trigger: false}
        - {get: bosh-init,    trigger: false}
        - {get: bats,         trigger: false}

      - {put: environment, params: {acquire: true}}

      - <<: *prepare-director

      - <<: *deploy-director

      - <<: *run-bats
        config:
          params:
            BAT_STEMCELL_NAME: bosh-aws-xen-ubuntu-trusty-go_agent

      - <<: *teardown

      - {put: environment, params: {release: environment}}

  - name: test-upgrade
    plan:
      - aggregate:
        - {get: bosh-release,    trigger: true}
        - {get: cpi-release,     trigger: true}
        - {get: stemcell,        trigger: true, resource: ubuntu-stemcell}
        - {get: pipelines,       trigger: false}
        - {get: bosh-init,       trigger: false}
        - {get: centos-stemcell, trigger: false} # pass-through

      - {put: environment, params: {acquire: true}}

      - <<: *prepare-director
        config:
          params:
            BOSH_RELEASE_URI:  https://bosh.cloudfoundry.org/d/github.com/cloudfoundry/bosh?v=229
            BOSH_RELEASE_SHA1: caad7d5353a76f81550868c54c6e0b441b378864
            CPI_RELEASE_URI:   https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=36
            CPI_RELEASE_SHA1:  db2a6c6cdd5ff9f77bf083e10118fa72e1f5e181
            STEMCELL_URI:      https://bosh.io/d/stemcells/bosh-aws-xen-ubuntu-trusty-go_agent?v=3143
            STEMCELL_SHA1:     222a546ccccd971a418d82aa6d3799c010164e9f

      - <<: *deploy-director

      - task: prepare-deployment
        file: pipelines/aws/tasks/prepare-deployment.yml
        config:
          params:
            RELEASE_NAME:              certification # TODO pull from secrets?
            STEMCELL_NAME:             bosh-aws-xen-ubuntu-trusty-go_agent
            BOSH_DIRECTOR_USERNAME:    {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD:    {{BOSH_DIRECTOR_PASSWORD}}

      - task: create-deployment
        file: pipelines/shared/tasks/create-deployment.yml
        config:
          params:
            BOSH_DIRECTOR_USERNAME:    {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD:    {{BOSH_DIRECTOR_PASSWORD}}
            RELEASE_NAME:              certification

      - <<: *prepare-director
        config:
          params:
            BOSH_RELEASE_URI: file://bosh-release/release.tgz
            CPI_RELEASE_URI:  file://cpi-release/release.tgz
            STEMCELL_URI:     file://stemcell/stemcell.tgz

      - <<: *deploy-director

      - task: recreate-deployment
        file: pipelines/shared/tasks/recreate-deployment.yml
        config:
          params:
            BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}

      - <<: *teardown

      - {put: environment, params: {release: environment}}

  - name: certify-centos
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-centos]}
        - {get: cpi-release,  trigger: true, passed: [bats-centos]}
        - {get: stemcell,     trigger: true, passed: [bats-centos, test-upgrade], resource: centos-stemcell}
        - {get: pipelines,    trigger: false}

      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        config:
          params:
            CPI_RELEASE_NAME: bosh-aws-cpi
            STEMCELL_NAME:    bosh-aws-xen-centos-7-go_agent

      - {put: receipt, params: {file: certification/*-receipt.json}}

  - name: certify-ubuntu
    plan:
      - aggregate:
        - {get: bosh-release, trigger: true, passed: [bats-ubuntu]}
        - {get: cpi-release,  trigger: true, passed: [bats-ubuntu]}
        - {get: stemcell,     trigger: true, passed: [bats-ubuntu, test-upgrade], resource: ubuntu-stemcell}
        - {get: pipelines,    trigger: false}

      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        config:
          params:
            CPI_RELEASE_NAME: bosh-aws-cpi
            STEMCELL_NAME:    bosh-aws-xen-ubuntu-trusty-go_agent

      - {put: receipt, params: {file: certification/*-receipt.json}}

resources:
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master

  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-aws-cpi-release

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-centos-7-go_agent

  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-ubuntu-trusty-go_agent

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: bosh-init-artifacts
      region_name: us-east-1

  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-receipt\.json
      region_name: us-east-1

  - name: environment
    type: pool
    source:
      pool: aws
      uri: git@github.com:cloudfoundry/bosh-cpi-environments.git
      branch: master
      private_key: {{github_deployment_key__bosh-cpi-environments}}
