---
groups:
  - name: certify-vcloud
    jobs:
      - bats-v5.5
      - bats-v5.6
      - certification

jobs:
  - name: bats-v5.5
    serial_groups: [group-v5.5]
    plan:
      - aggregate:
        - {get: cpi-release,      tags: [vcloud-v5.5], trigger: true}
        - {get: bosh-release,     tags: [vcloud-v5.5], trigger: true}
        - {get: stemcell,         tags: [vcloud-v5.5], trigger: true}
        - {get: pipelines,        tags: [vcloud-v5.5], trigger: false}
        - {get: bats,             tags: [vcloud-v5.5], trigger: false}
        - {get: bosh-init,        tags: [vcloud-v5.5], trigger: false}

      - task: prepare-director
        file: pipelines/vcloud/tasks/prepare-director.yml
        tags: [vcloud-v5.5]
        config:
          params:
            BOSH_RELEASE_URI:       file://bosh-release/release.tgz
            CPI_RELEASE_URI:        file://cpi-release/release.tgz
            STEMCELL_URI:           file://stemcell/stemcell.tgz
            VCLOUD_HOST:            {{VCLOUD_V5_5_HOST}}
            VCLOUD_USER:            {{VCLOUD_V5_5_USER}}
            VCLOUD_PASSWORD:        {{VCLOUD_V5_5_PASSWORD}}
            VCLOUD_VLAN:            {{VCLOUD_VLAN}}
            VCLOUD_ORG:             {{VCLOUD_V5_5_ORG}}
            VCLOUD_VDC:             {{VCLOUD_V5_5_VDC}}
            VCLOUD_VAPP:            {{VCLOUD_VAPP}}
            VCLOUD_CATALOG:         {{VCLOUD_CATALOG}}
            NETWORK_CIDR:           {{NETWORK_CIDR}}
            NETWORK_GATEWAY:        {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:       {{BATS_DIRECTOR_IP_ubuntu}}
            BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}

      - do:
        - task: deploy-director
          tags: [vcloud-v5.5]
          file: pipelines/shared/tasks/deploy-director.yml

        - task: prepare-bats
          tags: [vcloud-v5.5]
          file: pipelines/vcloud/tasks/prepare-bats.yml
          config:
            params:
              BATS_STEMCELL_NAME:   bosh-vcloud-esxi-ubuntu-trusty-go_agent
              VCLOUD_VLAN:          {{VCLOUD_VLAN}}
              VCLOUD_VAPP:          {{VCLOUD_VAPP}}
              NETWORK_CIDR:         {{NETWORK_CIDR}}
              NETWORK_GATEWAY:      {{NETWORK_GATEWAY}}
              BATS_DIRECTOR_IP:     {{BATS_DIRECTOR_IP_ubuntu}}
              BATS_IP1:             {{BATS_IP1_ubuntu}}
              BATS_IP2:             {{BATS_IP2_ubuntu}}
              BATS_RESERVED_RANGE1: {{BATS_RESERVED_RANGE1_ubuntu}}
              BATS_RESERVED_RANGE2: {{BATS_RESERVED_RANGE2_ubuntu}}
              BATS_STATIC_RANGE:    {{BATS_STATIC_RANGE_ubuntu}}

        - task: run-bats
          file: pipelines/shared/tasks/run-bats.yml
          tags: [vcloud-v5.5]

        ensure:
          task: teardown
          file: pipelines/shared/tasks/teardown.yml
          tags: [vcloud-v5.5]

  - name: bats-v5.6
    serial_groups: [group-v5.6]
    plan:
      - aggregate:
        - {get: cpi-release,      tags: [vcloud-v5.6], trigger: true}
        - {get: bosh-release,     tags: [vcloud-v5.6], trigger: true}
        - {get: stemcell,         tags: [vcloud-v5.6], trigger: true}
        - {get: pipelines,        tags: [vcloud-v5.6], trigger: false}
        - {get: bats,             tags: [vcloud-v5.6], trigger: false}
        - {get: bosh-init,        tags: [vcloud-v5.6], trigger: false}

      - task: prepare-director
        file: pipelines/vcloud/tasks/prepare-director.yml
        tags: [vcloud-v5.6]
        config:
          params:
            BOSH_RELEASE_URI:       file://bosh-release/release.tgz
            CPI_RELEASE_URI:        file://cpi-release/release.tgz
            STEMCELL_URI:           file://stemcell/stemcell.tgz
            VCLOUD_HOST:            {{VCLOUD_V5_6_HOST}}
            VCLOUD_USER:            {{VCLOUD_V5_6_USER}}
            VCLOUD_PASSWORD:        {{VCLOUD_V5_6_PASSWORD}}
            VCLOUD_VLAN:            {{VCLOUD_VLAN}}
            VCLOUD_ORG:             {{VCLOUD_V5_6_ORG}}
            VCLOUD_VDC:             {{VCLOUD_V5_6_VDC}}
            VCLOUD_VAPP:            {{VCLOUD_VAPP}}
            VCLOUD_CATALOG:         {{VCLOUD_CATALOG}}
            NETWORK_CIDR:           {{NETWORK_CIDR}}
            NETWORK_GATEWAY:        {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:       {{BATS_DIRECTOR_IP_ubuntu}}
            BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}

      - do:
        - task: deploy-director
          tags: [vcloud-v5.6]
          file: pipelines/shared/tasks/deploy-director.yml

        - task: prepare-bats
          tags: [vcloud-v5.6]
          file: pipelines/vcloud/tasks/prepare-bats.yml
          config:
            params:
              BATS_STEMCELL_NAME:   bosh-vcloud-esxi-ubuntu-trusty-go_agent
              VCLOUD_VLAN:          {{VCLOUD_VLAN}}
              VCLOUD_VAPP:          {{VCLOUD_VAPP}}
              NETWORK_CIDR:         {{NETWORK_CIDR}}
              NETWORK_GATEWAY:      {{NETWORK_GATEWAY}}
              BATS_DIRECTOR_IP:     {{BATS_DIRECTOR_IP_ubuntu}}
              BATS_IP1:             {{BATS_IP1_ubuntu}}
              BATS_IP2:             {{BATS_IP2_ubuntu}}
              BATS_RESERVED_RANGE1: {{BATS_RESERVED_RANGE1_ubuntu}}
              BATS_RESERVED_RANGE2: {{BATS_RESERVED_RANGE2_ubuntu}}
              BATS_STATIC_RANGE:    {{BATS_STATIC_RANGE_ubuntu}}

        - task: run-bats
          file: pipelines/shared/tasks/run-bats.yml
          tags: [vcloud-v5.6]

        ensure:
          task: teardown
          file: pipelines/shared/tasks/teardown.yml
          tags: [vcloud-v5.6]

  - name: certification
    plan:
      - aggregate:
        # NOTE: specify 'vcloud-v5.6' tag to take advantage of resource caching.
        - {get: cpi-release,      tags: [vcloud-v5.6], trigger: true, passed: [bats-v5.5, bats-v5.6]}
        - {get: bosh-release,     tags: [vcloud-v5.6], trigger: true, passed: [bats-v5.5, bats-v5.6]}
        - {get: stemcell,         tags: [vcloud-v5.6], trigger: true, passed: [bats-v5.5, bats-v5.6]}
        - {get: pipelines,        tags: [vcloud-v5.6], trigger: false}

      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        tags: [vcloud-v5.6]
        config:
          params:
            cpi_release_name: bosh-vcloud-cpi
            stemcell_name:    bosh-vcloud-esxi-ubuntu-trusty-go_agent

      - {put: receipt, tags: [vcloud-v5.6], params: {file: certification/*-receipt.json}}

resources:
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master

  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vcloud-cpi-release

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vcloud-esxi-ubuntu-trusty-go_agent

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: bosh-init-artifacts
      region_name: us-east-1

  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-receipt\.json
      region_name: us-east-1
