---
groups:
  - name: certify-vcloud
    jobs:
      - setup-v5.5
      - setup-v5.6
      - bats-v5.5
      - bats-v5.6
      - certify
      - teardown-v5.5
      - teardown-v5.6

jobs:
  - name: setup-v5.5
    serial_groups: [group-v5.5]
    plan:
      - aggregate:
        - {get: bosh-cpi-release, tags: [vcloud-v5.5], trigger: true}
        - {get: bosh-release,     tags: [vcloud-v5.5], trigger: true}
        - {get: stemcell,         tags: [vcloud-v5.5], trigger: true}
        - {get: pipelines,        tags: [vcloud-v5.5], trigger: false}
        - {get: bosh-init,        tags: [vcloud-v5.5], trigger: false}
        - {get: director-state,   tags: [vcloud-v5.5], trigger: false, resource: director-state-v5-5}

      - task: deploy
        file: pipelines/vcloud/tasks/deploy.yml
        tags: [vcloud-v5.5]
        config:
          params:
            base_os:              ubuntu
            network_type_to_test: manual
            VCLOUD_HOST:          {{VCLOUD_HOST_V5_5}}
            VCLOUD_USER:          {{VCLOUD_USER_V5_5}}
            VCLOUD_PASSWORD:      {{VCLOUD_PASSWORD_V5_5}}
            VCLOUD_VLAN:          {{VCLOUD_VLAN}}
            VCLOUD_ORG:           {{VCLOUD_ORG_V5_5}}
            VCLOUD_VDC:           {{VCLOUD_VDC_V5_5}}
            NETWORK_CIDR:         {{NETWORK_CIDR}}
            NETWORK_GATEWAY:      {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:     {{BATS_DIRECTOR_IP_ubuntu}}
        ensure:
          {put: director-state-v5-5, tags: [vcloud-v5.5], params: {from: deployment/director-state.json}}

  - name: setup-v5.6
    serial_groups: [group-v5.6]
    plan:
      - aggregate:
        - {get: bosh-cpi-release, tags: [vcloud-v5.6], trigger: true}
        - {get: bosh-release,     tags: [vcloud-v5.6], trigger: true}
        - {get: stemcell,         tags: [vcloud-v5.6], trigger: true}
        - {get: pipelines,        tags: [vcloud-v5.6], trigger: false}
        - {get: bosh-init,        tags: [vcloud-v5.6], trigger: false}
        - {get: director-state,   tags: [vcloud-v5.6], trigger: false, resource: director-state-v5-6}

      - task: deploy
        file: pipelines/vcloud/tasks/deploy.yml
        tags: [vcloud-v5.6]
        config:
          params:
            base_os:              ubuntu
            network_type_to_test: manual
            VCLOUD_HOST:          {{VCLOUD_HOST_V5_6}}
            VCLOUD_USER:          {{VCLOUD_USER_V5_6}}
            VCLOUD_PASSWORD:      {{VCLOUD_PASSWORD_V5_6}}
            VCLOUD_VLAN:          {{VCLOUD_VLAN}}
            VCLOUD_ORG:           {{VCLOUD_ORG_V5_6}}
            VCLOUD_VDC:           {{VCLOUD_VDC_V5_6}}
            NETWORK_CIDR:         {{NETWORK_CIDR}}
            NETWORK_GATEWAY:      {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:     {{BATS_DIRECTOR_IP_ubuntu}}
        ensure:
          {put: director-state-v5-6, tags: [vcloud-v5.6], params: {from: deployment/director-state.json}}

  - name: bats-v5.5
    serial_groups: [group-v5.5]
    plan:
      - aggregate:
        - {get: bosh-cpi-release, tags: [vcloud-v5.5], trigger: true, passed: [setup-v5.5]}
        - {get: bosh-release,     tags: [vcloud-v5.5], trigger: true, passed: [setup-v5.5]}
        - {get: stemcell,         tags: [vcloud-v5.5], trigger: true, passed: [setup-v5.5]}
        - {get: pipelines,        tags: [vcloud-v5.5], trigger: false}
        - {get: bats,             tags: [vcloud-v5.5], trigger: false}

      - task: test
        file: pipelines/vcloud/tasks/run-bats.yml
        tags: [vcloud-v5.5]
        config:
          params:
            base_os:              ubuntu
            BAT_NETWORKING:       manual
            BATS_STEMCELL_NAME:   bosh-vcloud-esxi-ubuntu-trusty-go_agent
            VCLOUD_VLAN:          {{VCLOUD_VLAN}}
            NETWORK_CIDR:         {{NETWORK_CIDR}}
            NETWORK_GATEWAY:      {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:     {{BATS_DIRECTOR_IP_ubuntu}}
            BATS_IP1:             {{BATS_IP1_ubuntu}}
            BATS_IP2:             {{BATS_IP2_ubuntu}}
            BATS_RESERVED_RANGE1: {{BATS_RESERVED_RANGE1_ubuntu}}
            BATS_RESERVED_RANGE2: {{BATS_RESERVED_RANGE2_ubuntu}}
            BATS_STATIC_RANGE:    {{BATS_STATIC_RANGE_ubuntu}}

  - name: bats-v5.6
    serial_groups: [group-v5.6]
    plan:
      - aggregate:
        - {get: bosh-cpi-release, tags: [vcloud-v5.6], trigger: true, passed: [setup-v5.6]}
        - {get: bosh-release,     tags: [vcloud-v5.6], trigger: true, passed: [setup-v5.6]}
        - {get: stemcell,         tags: [vcloud-v5.6], trigger: true, passed: [setup-v5.6]}
        - {get: pipelines,        tags: [vcloud-v5.6], trigger: false}
        - {get: bats,             tags: [vcloud-v5.6], trigger: false}

      - task: test
        file: pipelines/vcloud/tasks/run-bats.yml
        tags: [vcloud-v5.6]
        config:
          params:
            base_os:              ubuntu
            BAT_NETWORKING:       manual
            BATS_STEMCELL_NAME:   bosh-vcloud-esxi-ubuntu-trusty-go_agent
            VCLOUD_VLAN:          {{VCLOUD_VLAN}}
            NETWORK_CIDR:         {{NETWORK_CIDR}}
            NETWORK_GATEWAY:      {{NETWORK_GATEWAY}}
            BATS_DIRECTOR_IP:     {{BATS_DIRECTOR_IP_ubuntu}}
            BATS_IP1:             {{BATS_IP1_ubuntu}}
            BATS_IP2:             {{BATS_IP2_ubuntu}}
            BATS_RESERVED_RANGE1: {{BATS_RESERVED_RANGE1_ubuntu}}
            BATS_RESERVED_RANGE2: {{BATS_RESERVED_RANGE2_ubuntu}}
            BATS_STATIC_RANGE:    {{BATS_STATIC_RANGE_ubuntu}}

  - name: certification
    plan:
      - aggregate:
        # NOTE: arbitrary 'vcloud-v5.6' tag takes advantage of resource caching.
        - {get: bosh-cpi-release, tags: [vcloud-v5.6], trigger: true, passed: [bats-v5.5, bats-v5.6]}
        - {get: bosh-release,     tags: [vcloud-v5.6], trigger: true, passed: [bats-v5.5, bats-v5.6]}
        - {get: stemcell,         tags: [vcloud-v5.6], trigger: true, passed: [bats-v5.5, bats-v5.6]}
        - {get: pipelines,        tags: [vcloud-v5.6], trigger: false}

      - task: generate
        file: pipelines/vcloud/tasks/generate-receipt.yml
        config:
          params:
            bosh_release_name: bosh
            cpi_release_name:  bosh-vcloud-cpi
            stemcell_name:     bosh-vcloud-esxi-ubuntu-trusty-go_agent

      - put: receipt
        params:
          file: certification/*-receipt.json

  - name: teardown-v5.5
    serial_groups: [group-v5.5]
    plan:
      - {get: director-state, tags: [vcloud-v5.5], trigger: false, resource: director-state-v5-5}

      - task: teardown
        file: pipelines/vcloud/tasks/teardown.yml
        ensure:
          {put: director-state-v5-5, tags: [vcloud-v5.5], params: {from: deployment/director-state.json}}

  - name: teardown-v5.6
    serial_groups: [group-v5.6]
    plan:
      - {get: director-state, tags: [vcloud-v5.6], trigger: false, resource: director-state-v5-6}

      - task: teardown
        file: pipelines/vcloud/tasks/teardown.yml
        ensure:
          {put: director-state-v5-6, tags: [vcloud-v5.6], params: {from: deployment/director-state.json}}

resources:
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master

  - name: bosh-cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vcloud-cpi-release

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vcloud-esxi-ubuntu-trusty-go_agent

  - name: director-state-v5-5
    type: s3
    source:
      bucket: bosh-vcloud-cpi-ubuntu-state-files-v5-5
      versioned_file: director-state.json
      region_name: us-east-1
      access_key_id:     {{s3_vcloud_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vcloud_cpi_blobwriter_secret_key}}

  - name: director-state-v5-6
    type: s3
    source:
      bucket: bosh-vcloud-cpi-ubuntu-state-files-v5-6
      versioned_file: director-state.json
      region_name: us-east-1
      access_key_id:     {{s3_vcloud_cpi_blobwriter_access_key}}
      secret_access_key: {{s3_vcloud_cpi_blobwriter_secret_key}}

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: bosh-init-artifacts
      region_name: us-east-1

  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-receipt\.json
      region_name: us-east-1
