---
groups:
  - name: certify-vsphere
    jobs:
      - bats-centos
      - bats-ubuntu
      - test-upgrade
      - certify-centos
      - certify-ubuntu

shared:
  - &prepare-director
    task: prepare-director
    tags: [vsphere-v5.1]
    file: pipelines/vsphere/tasks/prepare-director.yml
    config:
      params:
        BOSH_RELEASE_URI:                       file://bosh-release/release.tgz
        CPI_RELEASE_URI:                        file://cpi-release/release.tgz
        STEMCELL_URI:                           file://stemcell/stemcell.tgz
        BOSH_DIRECTOR_USERNAME:                 {{BOSH_DIRECTOR_USERNAME}}
        BOSH_DIRECTOR_PASSWORD:                 {{BOSH_DIRECTOR_PASSWORD}}
        BOSH_VSPHERE_VCENTER:                   {{VCENTER_IP}}
        BOSH_VSPHERE_VCENTER_USER:              {{VCENTER_USER}}
        BOSH_VSPHERE_VCENTER_PASSWORD:          {{VCENTER_PASSWORD}}
        BOSH_VSPHERE_VERSION:                   {{VSPHERE_VERSION}}
        BOSH_VSPHERE_VCENTER_DC:                {{VCENTER_DC}}
        BOSH_VSPHERE_VCENTER_CLUSTER:           {{VCENTER_CLUSTER}}
        BOSH_VSPHERE_VCENTER_DATASTORE_PATTERN: {{VCENTER_DATASTORE_PATTERN}}
        BOSH_VSPHERE_VCENTER_VLAN:              {{VCENTER_VLAN}}
        BOSH_VSPHERE_VCENTER_VM_FOLDER:         {{VCENTER_VM_FOLDER}}
        BOSH_VSPHERE_VCENTER_TEMPLATE_FOLDER:   {{VCENTER_TEMPLATE_FOLDER}}
        BOSH_VSPHERE_VCENTER_DISK_PATH:         {{VCENTER_DISK_PATH}}

  - &deploy-director
    task: deploy-director
    tags: [vsphere-v5.1]
    file: pipelines/vsphere/tasks/deploy-director.yml
    config:
      params:
        BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
        BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}

  - &run-bats
    task: run-bats
    tags: [vsphere-v5.1]
    file: pipelines/vsphere/tasks/run-bats.yml
    config:
      params:
        BAT_STEMCELL_NAME: ""
        BAT_VCAP_PASSWORD: {{BAT_VCAP_PASSWORD}}

  - &teardown
    task: teardown
    tags: [vsphere-v5.1]
    file: pipelines/vsphere/tasks/teardown.yml
    config:
      params:
        BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
        BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}
        DEPLOYMENT_NAME:        certification

jobs:
  - name: bats-centos
    plan:
      - aggregate:
        - {get: bosh-release, tags: [vsphere-v5.1], trigger: true}
        - {get: cpi-release,  tags: [vsphere-v5.1], trigger: true}
        - {get: stemcell,     tags: [vsphere-v5.1], trigger: true, resource: centos-stemcell}
        - {get: pipelines,    tags: [vsphere-v5.1], trigger: false}
        - {get: bosh-init,    tags: [vsphere-v5.1], trigger: false}
        - {get: bats,         tags: [vsphere-v5.1], trigger: false}

      - {put: environment, tags: [vsphere-v5.1], params: {acquire: true}}

      - <<: *prepare-director

      - <<: *deploy-director

      - <<: *run-bats
        config:
          params:
            BAT_STEMCELL_NAME: bosh-vsphere-esxi-centos-7-go_agent

      - <<: *teardown

      - {put: environment, tags: [vsphere-v5.1], params: {release: environment}}

  - name: bats-ubuntu
    plan:
      - aggregate:
        - {get: bosh-release, tags: [vsphere-v5.1], trigger: true}
        - {get: cpi-release,  tags: [vsphere-v5.1], trigger: true}
        - {get: stemcell,     tags: [vsphere-v5.1], trigger: true, resource: ubuntu-stemcell}
        - {get: pipelines,    tags: [vsphere-v5.1], trigger: false}
        - {get: bosh-init,    tags: [vsphere-v5.1], trigger: false}
        - {get: bats,         tags: [vsphere-v5.1], trigger: false}

      - {put: environment, tags: [vsphere-v5.1], params: {acquire: true}}

      - <<: *prepare-director

      - <<: *deploy-director

      - <<: *run-bats
        config:
          params:
            BAT_STEMCELL_NAME: bosh-vsphere-esxi-ubuntu-trusty-go_agent

      - <<: *teardown

      - {put: environment, tags: [vsphere-v5.1], params: {release: environment}}

  - name: test-upgrade
    plan:
      - aggregate:
        - {get: bosh-release,    tags: [vsphere-v5.1], trigger: true}
        - {get: cpi-release,     tags: [vsphere-v5.1], trigger: true}
        - {get: stemcell,        tags: [vsphere-v5.1], trigger: true, resource: ubuntu-stemcell}
        - {get: pipelines,       tags: [vsphere-v5.1], trigger: false}
        - {get: bosh-init,       tags: [vsphere-v5.1], trigger: false}
        - {get: centos-stemcell, tags: [vsphere-v5.1], trigger: false} # pass-through

      - {put: environment, tags: [vsphere-v5.1], params: {acquire: true}}

      - <<: *prepare-director
        config:
          params:
            BOSH_RELEASE_URI:  https://bosh.cloudfoundry.org/d/github.com/cloudfoundry/bosh?v=229
            BOSH_RELEASE_SHA1: caad7d5353a76f81550868c54c6e0b441b378864
            CPI_RELEASE_URI:   https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release?v=14
            CPI_RELEASE_SHA1:  f2bd2e21542cd147d360e89d064a728a89c3790f
            STEMCELL_URI:      https://bosh.io/d/stemcells/bosh-vsphere-esxi-ubuntu-trusty-go_agent?v=3143
            STEMCELL_SHA1:     222a546ccccd971a418d82aa6d3799c010164e9f

      - <<: *deploy-director

      - task: prepare-deployment
        tags: [vsphere-v5.1]
        file: pipelines/vsphere/tasks/prepare-deployment.yml
        config:
          params:
            RELEASE_NAME:              certification #TODO pull from secrets?
            STEMCELL_NAME:             bosh-vsphere-esxi-ubuntu-trusty-go_agent
            BOSH_DIRECTOR_USERNAME:    {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD:    {{BOSH_DIRECTOR_PASSWORD}}
            BOSH_VSPHERE_VCENTER_VLAN: {{VCENTER_VLAN}}

      - task: create-deployment
        tags: [vsphere-v5.1]
        file: pipelines/vsphere/tasks/create-deployment.yml
        config:
          params:
            BOSH_DIRECTOR_USERNAME:    {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD:    {{BOSH_DIRECTOR_PASSWORD}}
            RELEASE_NAME:              certification

      - <<: *prepare-director
        config:
          params:
            BOSH_RELEASE_URI: file://bosh-release/release.tgz
            CPI_RELEASE_URI:  file://cpi-release/release.tgz
            STEMCELL_URI:     file://stemcell/stemcell.tgz

      - <<: *deploy-director

      - task: recreate-deployment
        tags: [vsphere-v5.1]
        file: pipelines/vsphere/tasks/recreate-deployment.yml
        config:
          params:
            BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}

      - <<: *teardown

      - {put: environment, tags: [vsphere-v5.1], params: {release: environment}}

  - name: certify-centos
    plan:
      - aggregate:
        - {get: bosh-release, tags: [vsphere-v5.1], trigger: true, passed: [bats-centos]}
        - {get: cpi-release,  tags: [vsphere-v5.1], trigger: true, passed: [bats-centos]}
        - {get: stemcell,     tags: [vsphere-v5.1], trigger: true, passed: [bats-centos, test-upgrade], resource: centos-stemcell}
        - {get: pipelines,    tags: [vsphere-v5.1], trigger: false}

      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        tags: [vsphere-v5.1]
        config:
          params:
            CPI_RELEASE_NAME: bosh-vsphere-cpi
            STEMCELL_NAME:    bosh-vsphere-esxi-centos-7-go_agent

      - {put: receipt, tags: [vsphere-v5.1], params: {file: certification/*-receipt.json}}

  - name: certify-ubuntu
    plan:
      - aggregate:
        - {get: bosh-release, tags: [vsphere-v5.1], trigger: true, passed: [bats-ubuntu]}
        - {get: cpi-release,  tags: [vsphere-v5.1], trigger: true, passed: [bats-ubuntu]}
        - {get: stemcell,     tags: [vsphere-v5.1], trigger: true, passed: [bats-ubuntu, test-upgrade], resource: ubuntu-stemcell}
        - {get: pipelines,    tags: [vsphere-v5.1], trigger: false}

      - task: generate
        file: pipelines/shared/tasks/generate-receipt.yml
        tags: [vsphere-v5.1]
        config:
          params:
            CPI_RELEASE_NAME: bosh-vsphere-cpi
            STEMCELL_NAME:    bosh-vsphere-esxi-ubuntu-trusty-go_agent

      - {put: receipt, tags: [vsphere-v5.1], params: {file: certification/*-receipt.json}}

resources:
  - name: pipelines
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/bosh-cpi-certification
      branch: master

  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-vsphere-cpi-release

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master

  - name: centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-centos-7-go_agent

  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

  - name: bosh-init
    type: s3
    source:
      regexp: bosh-init-([0-9.]+)-linux-amd64
      bucket: bosh-init-artifacts
      region_name: us-east-1

  - name: receipt
    type: s3
    source:
      access_key_id: {{certification__bucket_access_key}}
      secret_access_key: {{certification__bucket_secret_key}}
      bucket: {{certification__bucket}}
      regexp: .*-receipt\.json
      region_name: us-east-1

  - name: environment
    type: pool
    source:
      pool: vsphere-5.1
      uri: git@github.com:cloudfoundry/bosh-cpi-environments.git
      branch: master
      private_key: {{github_deployment_key__bosh-cpi-environments}}
