---
platform: linux
image: docker:///boshcpi/cpi-certification

inputs:
  - name: pipelines

outputs:
  - name: deployment-manifest

run:
  path: pipelines/aws/tasks/prepare-deployment.sh

params:
  AWS_ACCESS_KEY:         ""
  AWS_SECRET_KEY:         ""
  AWS_REGION_NAME:        ""
  AWS_STACK_NAME:         ""
  BOSH_DIRECTOR_USERNAME: ""
  BOSH_DIRECTOR_PASSWORD: ""
  DEPLOYMENT_NAME:        ""
  RELEASE_NAME:           ""
  STEMCELL_NAME:          ""
