---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines

run:
  path: pipelines/aws/tasks/recreate-infrastructure.sh

params:
  AWS_ACCESS_KEY:  ""
  AWS_SECRET_KEY:  ""
  AWS_REGION_NAME: ""
  AWS_STACK_NAME:  ""
