---
platform: linux
image: image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: director-config
  - name: bosh-init
  - name: bosh-release
  - name: cpi-release
  - name: stemcell

outputs:
  - name: director-state

run:
  path: pipelines/shared/tasks/deploy-director.sh

params:
  BOSH_INIT_LOG_LEVEL:    info
  BOSH_DIRECTOR_USERNAME: ""
  BOSH_DIRECTOR_PASSWORD: ""
