---
platform: linux
image: docker:///boshcpi/cpi-certification

inputs:
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: pipelines
outputs:
  - name: certification

run:
  path: pipelines/shared/tasks/generate-receipt.sh

params:
  CPI_RELEASE_NAME: ""
  STEMCELL_NAME:    ""
