---
platform: linux
image: image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: bats
  - name: bats-config
  - name: stemcell

run:
  path: pipelines/shared/tasks/run-bats.sh
