---
platform: linux
image: image_resource:
  type: docker-image
  source: {repository: boshcpi/cpi-certification}

inputs:
  - name: pipelines
  - name: director-config
  - name: director-state
  - name: bosh-init
  - name: bosh-release
  - name: cpi-release
  - name: stemcell

outputs:
  - name: new-director-state

params:
  DEPLOYMENT_NAME: ""

run:
  path: pipelines/shared/tasks/test-upgrade.sh
